### ISSUE TITLE
Solution Import Error

### ISSUE THREAD

**Issue by mhammons** [santoshCRM/CRMSingleCalender#1]
When I try to install the solution I get the error below.

The import of the solution AllInOneCalender failed. The following components are missing in your system and are not included in the solution. Import the managed solutions that contain these components (GoogleMap (1.0.0.0)) and then try importing this solution again.
--

**Comment by santoshCRM** [comment]
Issue is resolved now. Now no need to install solution google -map (https://github.com/santoshCRM/Google-Map/blob/master/GoogleMapSearch_1_0_0_0_managed.zip)
